// Replace direct image URLs with a webp proxy generated by images.weserv.nl for better compression without uploading binaries
const webpFor = (url, quality = 75, width = null) => {
  // images.weserv.nl expects the URL without protocol
  try {
    const u = new URL(url);
    const path = u.hostname + u.pathname;
    let q = `&output=webp&quality=${quality}`;
    let w = width ? `&w=${width}` : '';
    return `https://images.weserv.nl/?url=${path}${q}${w}`;
  } catch (e) {
    return url; // fallback
  }
};

// Update existing data-bg occurrences generated earlier to point to webp proxy
const updateDataBgToWebpProxy = () => {
  document.querySelectorAll('[data-bg]').forEach(el => {
    const original = el.getAttribute('data-bg');
    if (!original) return;
    const proxy = webpFor(original, 75);
    el.setAttribute('data-bg', proxy);
  });
  // update preload link if present
  const preload = document.querySelector('link[rel="preload"][as="image"]');
  if (preload && preload.href) {
    try {
      const p = new URL(preload.href);
      const proxy = webpFor(preload.href, 75);
      preload.href = proxy;
    } catch (e) {
      // ignore
    }
  }
};

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', updateDataBgToWebpProxy);
} else {
  updateDataBgToWebpProxy();
}
